CREATE DATABASE customer_behavior;
USE customer_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customer used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND
      purchase_amount > (SELECT AVG(purchase_amount) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
 SELECT 
    item_purchased,
    AVG(review_rating) AS "Average Review Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Review Rating" DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between staandard and express shipping
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS "Average Purchase Amount"
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY Shipping_type;


-- Q5. Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS "Average Spend",
    ROUND(SUM(purchase_amount),2) AS "Total Revenue"
FROM customer
GROUP BY subscription_status
ORDER BY "Total Revenue", "Average Spend" DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
 SELECT
    item_purchased,
    ROUND (SUM(CASE WHEN discount_applied = 'YES'
             THEN 1
             ELSE 0
        END)/COUNT(*) * 100, 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. ** Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT customer_id, 
           previous_purchases,
           CASE
                WHEN previous_purchases = 1 THEN 'NEW'
                WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
                ELSE 'Loyal'
            END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS(
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased    
)
SELECT 
    category,
    item_rank,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeated_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
Order BY total_revenue DESC;